### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/Lifetree#5]
### Code
* [x] Proper readable and maintable code with consistent spacing and indentation
* [x] Functions follow the "Do One Thing" rule (single-responsibility)
* [x] Followed DRY (Don’t Repeat Yourself)
* [x] Added comments wherever required
* [x] Proper naming conventions
* [x] Avoided deep nesting

### Readme
* [x] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [x] Description (why this project exists)
* [x] Features (working of the project)
* [x] Setup (Quick start instructions with how to download and use your project)
* [x] Contributing (How can others contribute?)
* [x] License ("This project is licensed under the <your license>")

### Tests and CI/CD
* [ ] Wrote tests
* [x] Deployed the project (if possible)
* [ ] Added CI/CD tools to your project (maybe CircleCI or TravisCI) (if possible)

**Comment by anandbaburajan** [comment]
@alwin48 & @aryanbaburajan, great work so far! Thanks for contributing! There's an open PR and the project looks like it needs some more improvements. Feel free to let me know if you've any doubts and when I should review again! :D

**Comment by anandbaburajan** [comment]
Also, there's a small typo in your readme. Please replace 'Discussions about LifeTree is placed on our Gitter Chat Anybody is welcome to join these conversations.' with:

'Discussions about LifeTree take place on our Gitter Chat. Anyone is welcome to join the conversations.'

**Comment by anandbaburajan** [comment]
Also, you can add a section in the readme for 'potential improvements'.
